export interface Agent {
  id: string;
  name: string;
  category: string;
  description: string;
  shortDesc: string;
  tokenSavings: string;
  timeSavings: string;
  useCases: string[];
  features: string[];
  inputTypes: string[];
  outputTypes: string[];
  difficulty: "beginner" | "intermediate" | "advanced";
  popularity: number;
  badge?: string;
}

export const agents: Agent[] = [
  // Development & Coding Agents
  {
    id: "code-review-pro",
    name: "Code Review Pro",
    category: "development",
    description: "Comprehensive code analysis with security, performance, and best practices review. Catches bugs before production.",
    shortDesc: "Professional code review with actionable feedback",
    tokenSavings: "75%",
    timeSavings: "2hrs per review",
    useCases: ["Pull request reviews", "Security audits", "Code quality checks", "Best practices enforcement"],
    features: ["Security scanning", "Performance analysis", "Style guide checks", "Refactoring suggestions"],
    inputTypes: ["Code files", "Git diffs", "Pull requests"],
    outputTypes: ["Review report", "Issue list", "Suggestions"],
    difficulty: "intermediate",
    popularity: 95,
    badge: "Popular"
  },
  {
    id: "bug-hunter",
    name: "Bug Hunter",
    category: "development",
    description: "Systematic debugging with root cause analysis. Identifies bugs and provides fixes with explanations.",
    shortDesc: "Find and fix bugs 10x faster",
    tokenSavings: "80%",
    timeSavings: "3hrs per bug",
    useCases: ["Debug complex issues", "Root cause analysis", "Performance bottlenecks", "Memory leaks"],
    features: ["Stack trace analysis", "Variable inspection", "Fix suggestions", "Test case generation"],
    inputTypes: ["Error messages", "Code context", "Logs"],
    outputTypes: ["Root cause", "Fix code", "Prevention tips"],
    difficulty: "intermediate",
    popularity: 92
  },
  {
    id: "api-builder",
    name: "API Builder",
    category: "development",
    description: "RESTful and GraphQL API design with documentation. Generates complete API specifications and code.",
    shortDesc: "Design and document APIs instantly",
    tokenSavings: "70%",
    timeSavings: "5hrs per API",
    useCases: ["REST API design", "GraphQL schemas", "OpenAPI specs", "API documentation"],
    features: ["Endpoint design", "Schema generation", "Auth patterns", "Rate limiting"],
    inputTypes: ["Requirements", "Data models", "Use cases"],
    outputTypes: ["API spec", "Code stubs", "Documentation"],
    difficulty: "intermediate",
    popularity: 88
  },
  {
    id: "database-architect",
    name: "Database Architect",
    category: "development",
    description: "Schema design, optimization, and migration scripts for all major databases.",
    shortDesc: "Optimize database design and performance",
    tokenSavings: "65%",
    timeSavings: "4hrs per schema",
    useCases: ["Schema design", "Query optimization", "Migration planning", "Index strategies"],
    features: ["ERD generation", "Normalization", "Performance tuning", "Migration scripts"],
    inputTypes: ["Requirements", "Current schema", "Query patterns"],
    outputTypes: ["Schema DDL", "Migration scripts", "Index recommendations"],
    difficulty: "advanced",
    popularity: 85
  },
  {
    id: "test-suite-generator",
    name: "Test Suite Generator",
    category: "development",
    description: "Comprehensive test creation for unit, integration, and E2E testing with coverage analysis.",
    shortDesc: "Generate complete test suites automatically",
    tokenSavings: "85%",
    timeSavings: "6hrs per suite",
    useCases: ["Unit tests", "Integration tests", "E2E tests", "Test coverage"],
    features: ["Test generation", "Mock creation", "Coverage analysis", "Edge cases"],
    inputTypes: ["Source code", "Requirements", "API specs"],
    outputTypes: ["Test files", "Mock data", "Coverage report"],
    difficulty: "intermediate",
    popularity: 87
  },
  {
    id: "refactoring-master",
    name: "Refactoring Master",
    category: "development",
    description: "Code modernization and technical debt reduction with safe refactoring strategies.",
    shortDesc: "Transform legacy code safely",
    tokenSavings: "70%",
    timeSavings: "8hrs per refactor",
    useCases: ["Legacy modernization", "Code cleanup", "Pattern implementation", "Performance optimization"],
    features: ["Code smell detection", "Refactoring plan", "Test preservation", "Incremental changes"],
    inputTypes: ["Legacy code", "Target patterns", "Constraints"],
    outputTypes: ["Refactored code", "Migration plan", "Test updates"],
    difficulty: "advanced",
    popularity: 86
  },
  {
    id: "devops-pipeline",
    name: "DevOps Pipeline",
    category: "development",
    description: "CI/CD pipeline configuration for GitHub Actions, GitLab, Jenkins, and cloud platforms.",
    shortDesc: "Automate deployment pipelines",
    tokenSavings: "80%",
    timeSavings: "10hrs per pipeline",
    useCases: ["CI/CD setup", "Deployment automation", "Testing pipelines", "Infrastructure as code"],
    features: ["Pipeline generation", "Docker configs", "Kubernetes manifests", "Monitoring setup"],
    inputTypes: ["Tech stack", "Deployment targets", "Requirements"],
    outputTypes: ["Pipeline configs", "Dockerfiles", "K8s manifests"],
    difficulty: "advanced",
    popularity: 89
  },
  {
    id: "security-auditor",
    name: "Security Auditor",
    category: "development",
    description: "Comprehensive security analysis with OWASP compliance and vulnerability detection.",
    shortDesc: "Find security vulnerabilities fast",
    tokenSavings: "90%",
    timeSavings: "12hrs per audit",
    useCases: ["Security audits", "Vulnerability scanning", "Compliance checks", "Penetration testing"],
    features: ["OWASP scanning", "Dependency checks", "Code analysis", "Remediation guides"],
    inputTypes: ["Source code", "Dependencies", "Infrastructure"],
    outputTypes: ["Security report", "Vulnerability list", "Fix recommendations"],
    difficulty: "advanced",
    popularity: 91
  },
  {
    id: "performance-optimizer",
    name: "Performance Optimizer",
    category: "development",
    description: "Identify bottlenecks and optimize code for speed and efficiency.",
    shortDesc: "Make code 10x faster",
    tokenSavings: "75%",
    timeSavings: "6hrs per optimization",
    useCases: ["Performance tuning", "Memory optimization", "Query optimization", "Load testing"],
    features: ["Profiling analysis", "Bottleneck detection", "Optimization suggestions", "Benchmarking"],
    inputTypes: ["Code", "Performance metrics", "Requirements"],
    outputTypes: ["Optimized code", "Performance report", "Benchmarks"],
    difficulty: "advanced",
    popularity: 88
  },
  {
    id: "documentation-writer",
    name: "Documentation Writer",
    category: "development",
    description: "Generate comprehensive technical documentation, README files, and API docs.",
    shortDesc: "Create perfect documentation",
    tokenSavings: "80%",
    timeSavings: "5hrs per doc",
    useCases: ["API documentation", "README files", "User guides", "Technical specs"],
    features: ["Auto-generation", "Markdown formatting", "Code examples", "Diagrams"],
    inputTypes: ["Code", "APIs", "Requirements"],
    outputTypes: ["Documentation", "README", "Guides"],
    difficulty: "beginner",
    popularity: 90
  },

  // Content & Writing Agents
  {
    id: "seo-blog-writer",
    name: "SEO Blog Writer",
    category: "content",
    description: "Create SEO-optimized blog posts that rank on Google with keyword research and content structure.",
    shortDesc: "Rank #1 on Google with AI content",
    tokenSavings: "90%",
    timeSavings: "4hrs per article",
    useCases: ["Blog posts", "SEO articles", "Content marketing", "Keyword optimization"],
    features: ["Keyword research", "Content structure", "Meta descriptions", "Internal linking"],
    inputTypes: ["Topic", "Keywords", "Competitor URLs"],
    outputTypes: ["Blog post", "Meta tags", "Content brief"],
    difficulty: "intermediate",
    popularity: 94,
    badge: "Popular"
  },
  {
    id: "email-campaign-creator",
    name: "Email Campaign Creator",
    category: "content",
    description: "Design high-converting email campaigns with A/B testing variants and personalization.",
    shortDesc: "Emails that convert",
    tokenSavings: "85%",
    timeSavings: "3hrs per campaign",
    useCases: ["Email marketing", "Newsletters", "Drip campaigns", "Sales sequences"],
    features: ["Subject line optimization", "Personalization", "A/B variants", "Call-to-action"],
    inputTypes: ["Product info", "Audience", "Goals"],
    outputTypes: ["Email copy", "Subject lines", "Campaign strategy"],
    difficulty: "intermediate",
    popularity: 89
  },
  {
    id: "social-media-manager",
    name: "Social Media Manager",
    category: "content",
    description: "Create engaging social media content calendars with platform-specific optimization.",
    shortDesc: "Go viral on social media",
    tokenSavings: "80%",
    timeSavings: "10hrs per week",
    useCases: ["Social posts", "Content calendars", "Hashtag research", "Engagement strategies"],
    features: ["Platform optimization", "Hashtag generation", "Content scheduling", "Trend analysis"],
    inputTypes: ["Brand voice", "Topics", "Goals"],
    outputTypes: ["Social posts", "Content calendar", "Hashtags"],
    difficulty: "beginner",
    popularity: 91,
    badge: "Trending"
  },
  {
    id: "copywriting-expert",
    name: "Copywriting Expert",
    category: "content",
    description: "Persuasive sales copy, landing pages, and ad copy that converts visitors into customers.",
    shortDesc: "Copy that sells",
    tokenSavings: "75%",
    timeSavings: "3hrs per page",
    useCases: ["Sales pages", "Ad copy", "Landing pages", "Product descriptions"],
    features: ["Conversion optimization", "A/B testing", "Emotional triggers", "Call-to-action"],
    inputTypes: ["Product details", "Target audience", "USP"],
    outputTypes: ["Sales copy", "Headlines", "CTAs"],
    difficulty: "intermediate",
    popularity: 90
  },
  {
    id: "technical-writer",
    name: "Technical Writer",
    category: "content",
    description: "Clear technical documentation, user manuals, and help articles.",
    shortDesc: "Complex topics made simple",
    tokenSavings: "80%",
    timeSavings: "6hrs per guide",
    useCases: ["User manuals", "Help documentation", "Technical guides", "API docs"],
    features: ["Clear structure", "Visual aids", "Step-by-step guides", "Glossaries"],
    inputTypes: ["Technical info", "Audience level", "Product details"],
    outputTypes: ["Documentation", "Guides", "FAQs"],
    difficulty: "intermediate",
    popularity: 86
  },
  {
    id: "video-script-writer",
    name: "Video Script Writer",
    category: "content",
    description: "Engaging video scripts for YouTube, TikTok, and educational content.",
    shortDesc: "Scripts that keep viewers watching",
    tokenSavings: "85%",
    timeSavings: "4hrs per script",
    useCases: ["YouTube videos", "Course content", "Explainer videos", "Social media videos"],
    features: ["Hook creation", "Story structure", "CTA placement", "Timing optimization"],
    inputTypes: ["Topic", "Video length", "Platform"],
    outputTypes: ["Script", "Shot list", "Timestamps"],
    difficulty: "intermediate",
    popularity: 88
  },
  {
    id: "newsletter-curator",
    name: "Newsletter Curator",
    category: "content",
    description: "Curate and write engaging newsletters that subscribers actually read.",
    shortDesc: "Newsletters people love",
    tokenSavings: "70%",
    timeSavings: "3hrs per issue",
    useCases: ["Weekly newsletters", "Industry roundups", "Company updates", "Content curation"],
    features: ["Content curation", "Subject optimization", "Segmentation", "Analytics"],
    inputTypes: ["Topics", "Sources", "Audience"],
    outputTypes: ["Newsletter content", "Subject lines", "Segments"],
    difficulty: "beginner",
    popularity: 84
  },
  {
    id: "press-release-pro",
    name: "Press Release Pro",
    category: "content",
    description: "Professional press releases that get media attention.",
    shortDesc: "Get featured in the news",
    tokenSavings: "75%",
    timeSavings: "2hrs per release",
    useCases: ["Product launches", "Company news", "Event announcements", "Media outreach"],
    features: ["News angle", "Quote generation", "Distribution strategy", "Media contacts"],
    inputTypes: ["News item", "Key facts", "Quotes"],
    outputTypes: ["Press release", "Media pitch", "Distribution list"],
    difficulty: "intermediate",
    popularity: 82
  },
  {
    id: "case-study-creator",
    name: "Case Study Creator",
    category: "content",
    description: "Compelling case studies that showcase success and drive sales.",
    shortDesc: "Success stories that sell",
    tokenSavings: "80%",
    timeSavings: "5hrs per study",
    useCases: ["Customer success", "ROI demonstration", "Social proof", "Sales enablement"],
    features: ["Story structure", "Data visualization", "Quote integration", "Results focus"],
    inputTypes: ["Client data", "Results", "Testimonials"],
    outputTypes: ["Case study", "Executive summary", "Graphics"],
    difficulty: "intermediate",
    popularity: 85
  },
  {
    id: "content-repurposer",
    name: "Content Repurposer",
    category: "content",
    description: "Transform one piece of content into multiple formats for maximum reach.",
    shortDesc: "One content, 10 formats",
    tokenSavings: "90%",
    timeSavings: "8hrs per piece",
    useCases: ["Content multiplication", "Cross-platform posting", "Format conversion", "Content atomization"],
    features: ["Format adaptation", "Platform optimization", "Key point extraction", "Visual creation"],
    inputTypes: ["Original content", "Target platforms", "Goals"],
    outputTypes: ["Multiple formats", "Platform variants", "Content calendar"],
    difficulty: "beginner",
    popularity: 87
  },
  {
    id: "storytelling-expert",
    name: "Storytelling Expert",
    category: "content",
    description: "Craft compelling narratives that connect emotionally with your audience.",
    shortDesc: "Stories that resonate",
    tokenSavings: "75%",
    timeSavings: "3hrs per story",
    useCases: ["Brand stories", "About pages", "Founder stories", "Customer narratives"],
    features: ["Story arc", "Emotional hooks", "Character development", "Conflict resolution"],
    inputTypes: ["Key facts", "Message", "Audience"],
    outputTypes: ["Story narrative", "Story frameworks", "Emotional beats"],
    difficulty: "intermediate",
    popularity: 86
  },

  // Business & Productivity Agents
  {
    id: "strategic-planner",
    name: "Strategic Planner",
    category: "business",
    description: "Transform business ideas into actionable strategic plans with SMART goals, KPIs, and resource allocation.",
    shortDesc: "Turn ideas into executable strategies",
    tokenSavings: "70%",
    timeSavings: "8hrs per plan",
    useCases: ["Strategic planning", "Goal setting", "Resource allocation", "Roadmap creation"],
    features: ["SMART goals", "90-day sprints", "Risk analysis", "KPI definition"],
    inputTypes: ["Business objectives", "Constraints", "Resources"],
    outputTypes: ["Strategic plan", "Roadmap", "Success metrics"],
    difficulty: "intermediate",
    popularity: 89,
    badge: "Essential"
  },
  {
    id: "productivity-optimizer",
    name: "Productivity Optimizer",
    category: "business",
    description: "Analyze workflows and eliminate inefficiencies. Create systems that save hours every week.",
    shortDesc: "Maximize team and personal productivity",
    tokenSavings: "75%",
    timeSavings: "10hrs per week",
    useCases: ["Time management", "Workflow optimization", "Meeting reduction", "Task automation"],
    features: ["Time audit", "Automation finder", "Schedule optimization", "Focus protection"],
    inputTypes: ["Current workflow", "Pain points", "Tools available"],
    outputTypes: ["Optimized schedule", "Automation plan", "Tool recommendations"],
    difficulty: "beginner",
    popularity: 91,
    badge: "Popular"
  },
  {
    id: "decision-maker",
    name: "Decision Maker",
    category: "business",
    description: "Make complex business decisions with confidence using decision matrices and scenario analysis.",
    shortDesc: "Data-driven decision support",
    tokenSavings: "80%",
    timeSavings: "4hrs per decision",
    useCases: ["Strategic decisions", "Vendor selection", "Investment choices", "Risk assessment"],
    features: ["Decision matrix", "Cost-benefit analysis", "Risk evaluation", "Scenario planning"],
    inputTypes: ["Options", "Criteria", "Constraints"],
    outputTypes: ["Decision matrix", "Recommendation", "Risk analysis"],
    difficulty: "intermediate",
    popularity: 86
  },
  {
    id: "process-automator",
    name: "Process Automator",
    category: "business",
    description: "Identify and automate repetitive tasks. Design workflows that save time and reduce errors.",
    shortDesc: "Automate repetitive business processes",
    tokenSavings: "85%",
    timeSavings: "15hrs per process",
    useCases: ["Process automation", "Workflow design", "Integration planning", "Error reduction"],
    features: ["Process mapping", "Automation ROI", "Tool selection", "Implementation guide"],
    inputTypes: ["Current process", "Volume metrics", "Tools"],
    outputTypes: ["Automation plan", "ROI calculation", "Implementation steps"],
    difficulty: "intermediate",
    popularity: 88
  },
  {
    id: "okr-architect",
    name: "OKR Architect",
    category: "business",
    description: "Create aligned OKRs from company to individual level with measurable key results.",
    shortDesc: "Design effective OKRs that drive results",
    tokenSavings: "70%",
    timeSavings: "6hrs per quarter",
    useCases: ["Goal setting", "Team alignment", "Performance tracking", "Quarterly planning"],
    features: ["OKR creation", "Alignment mapping", "Progress tracking", "Review templates"],
    inputTypes: ["Company mission", "Strategic focus", "Team structure"],
    outputTypes: ["OKR sets", "Tracking templates", "Review framework"],
    difficulty: "intermediate",
    popularity: 84
  },
  {
    id: "crisis-manager",
    name: "Crisis Manager",
    category: "business",
    description: "Rapid response plans for business crises with communication templates and recovery strategies.",
    shortDesc: "Navigate crises with confidence",
    tokenSavings: "90%",
    timeSavings: "Critical hours",
    useCases: ["Crisis response", "Damage control", "Communication planning", "Recovery strategy"],
    features: ["24-hour action plan", "Stakeholder messaging", "Media response", "Recovery roadmap"],
    inputTypes: ["Crisis type", "Impact scope", "Resources"],
    outputTypes: ["Response plan", "Communication templates", "Recovery timeline"],
    difficulty: "advanced",
    popularity: 82
  },
  {
    id: "negotiation-strategist",
    name: "Negotiation Strategist",
    category: "business",
    description: "Prepare winning negotiation strategies with tactics, counters, and psychological insights.",
    shortDesc: "Win negotiations while maintaining relationships",
    tokenSavings: "75%",
    timeSavings: "5hrs per negotiation",
    useCases: ["Contract negotiations", "Salary discussions", "Vendor terms", "Partnership deals"],
    features: ["BATNA analysis", "Concession planning", "Tactic counters", "Value creation"],
    inputTypes: ["Negotiation context", "Goals", "Constraints"],
    outputTypes: ["Strategy playbook", "Tactics guide", "Walk-away triggers"],
    difficulty: "advanced",
    popularity: 87
  },
  {
    id: "remote-team-leader",
    name: "Remote Team Leader",
    category: "business",
    description: "Build high-performing remote teams with async workflows and engagement strategies.",
    shortDesc: "Master remote team management",
    tokenSavings: "70%",
    timeSavings: "8hrs per week",
    useCases: ["Remote management", "Team building", "Async collaboration", "Performance tracking"],
    features: ["Communication protocols", "Meeting optimization", "Culture building", "Burnout prevention"],
    inputTypes: ["Team structure", "Time zones", "Challenges"],
    outputTypes: ["Management playbook", "Communication plan", "Culture initiatives"],
    difficulty: "intermediate",
    popularity: 90,
    badge: "Trending"
  },
  {
    id: "change-leader",
    name: "Change Leader",
    category: "business",
    description: "Lead organizational change with minimal resistance and maximum adoption.",
    shortDesc: "Drive successful organizational change",
    tokenSavings: "75%",
    timeSavings: "12hrs per initiative",
    useCases: ["Change management", "Digital transformation", "Restructuring", "Process changes"],
    features: ["Stakeholder mapping", "Resistance mitigation", "Communication cascade", "Adoption tracking"],
    inputTypes: ["Change type", "Impact scope", "Timeline"],
    outputTypes: ["Change plan", "Communication strategy", "Success metrics"],
    difficulty: "advanced",
    popularity: 83
  },
  {
    id: "partnership-builder",
    name: "Partnership Builder",
    category: "business",
    description: "Structure win-win partnerships with clear terms, governance, and success metrics.",
    shortDesc: "Create strategic partnerships that scale",
    tokenSavings: "80%",
    timeSavings: "10hrs per partnership",
    useCases: ["Strategic alliances", "Channel partnerships", "Integration partners", "Joint ventures"],
    features: ["Value proposition", "Revenue models", "Contract terms", "Governance structure"],
    inputTypes: ["Partnership goals", "Partner profile", "Resources"],
    outputTypes: ["Partnership framework", "Term sheet", "Success plan"],
    difficulty: "advanced",
    popularity: 85
  },

  // Research & Analysis Agents
  {
    id: "market-intelligence-pro",
    name: "Market Intelligence Pro",
    category: "research",
    description: "Comprehensive market analysis with competitor intelligence, industry trends, and growth opportunities. Delivers actionable insights for strategic planning and market entry decisions.",
    shortDesc: "Deep market analysis and competitive intelligence",
    tokenSavings: "82%",
    timeSavings: "15hrs per report",
    useCases: ["Market sizing", "Competitive analysis", "Industry trends", "Market entry strategy"],
    features: ["Competitor mapping", "SWOT analysis", "Market forecasting", "Opportunity identification"],
    inputTypes: ["Industry data", "Company reports", "Market segments"],
    outputTypes: ["Market report", "Competitor profiles", "Growth opportunities"],
    difficulty: "advanced",
    popularity: 91,
    badge: "Popular"
  },
  {
    id: "academic-researcher",
    name: "Academic Researcher",
    category: "research",
    description: "Systematic literature reviews, citation analysis, and research methodology guidance. Accelerates academic research with comprehensive source evaluation and synthesis.",
    shortDesc: "Accelerate academic research and literature reviews",
    tokenSavings: "78%",
    timeSavings: "20hrs per review",
    useCases: ["Literature reviews", "Citation analysis", "Research proposals", "Methodology design"],
    features: ["Source credibility scoring", "Gap analysis", "Citation networks", "Research frameworks"],
    inputTypes: ["Research questions", "Academic papers", "Keywords"],
    outputTypes: ["Literature review", "Research gaps", "Methodology plan"],
    difficulty: "intermediate",
    popularity: 87
  },
  {
    id: "fact-checker-pro",
    name: "Fact-Checker Pro",
    category: "research",
    description: "Rigorous fact verification with source authentication and bias detection. Ensures information accuracy for journalism, content creation, and decision-making.",
    shortDesc: "Verify facts with source authentication",
    tokenSavings: "75%",
    timeSavings: "3hrs per article",
    useCases: ["News verification", "Content fact-checking", "Claim verification", "Source validation"],
    features: ["Source credibility", "Cross-referencing", "Bias detection", "Evidence strength"],
    inputTypes: ["Claims", "Articles", "Statements"],
    outputTypes: ["Verification report", "Source list", "Credibility score"],
    difficulty: "beginner",
    popularity: 89,
    badge: "Essential"
  },
  {
    id: "survey-analyst",
    name: "Survey Analyst",
    category: "research",
    description: "Advanced survey design and statistical analysis with actionable insights. Transforms raw survey data into strategic recommendations and visualizations.",
    shortDesc: "Design surveys and analyze results professionally",
    tokenSavings: "80%",
    timeSavings: "12hrs per survey",
    useCases: ["Survey design", "Data analysis", "Statistical testing", "Insight generation"],
    features: ["Question optimization", "Statistical analysis", "Bias correction", "Visualization"],
    inputTypes: ["Survey objectives", "Raw responses", "Demographics"],
    outputTypes: ["Analysis report", "Insights", "Recommendations"],
    difficulty: "intermediate",
    popularity: 84
  },
  {
    id: "data-detective",
    name: "Data Detective",
    category: "research",
    description: "Uncover hidden patterns and anomalies in complex datasets. Provides statistical analysis, trend identification, and predictive insights for data-driven decisions.",
    shortDesc: "Discover hidden insights in your data",
    tokenSavings: "85%",
    timeSavings: "8hrs per analysis",
    useCases: ["Pattern recognition", "Anomaly detection", "Trend analysis", "Predictive modeling"],
    features: ["Statistical testing", "Correlation analysis", "Outlier detection", "Predictive models"],
    inputTypes: ["Datasets", "Metrics", "Time series"],
    outputTypes: ["Analysis report", "Visualizations", "Predictions"],
    difficulty: "advanced",
    popularity: 88
  },
  {
    id: "industry-trend-tracker",
    name: "Industry Trend Tracker",
    category: "research",
    description: "Real-time industry monitoring with trend forecasting and impact analysis. Identifies emerging opportunities and potential disruptions across sectors.",
    shortDesc: "Track and predict industry trends",
    tokenSavings: "77%",
    timeSavings: "10hrs per week",
    useCases: ["Trend monitoring", "Disruption analysis", "Opportunity spotting", "Strategic foresight"],
    features: ["Trend scoring", "Signal detection", "Impact assessment", "Timeline forecasting"],
    inputTypes: ["Industry news", "Patents", "Funding data"],
    outputTypes: ["Trend report", "Opportunity map", "Risk alerts"],
    difficulty: "intermediate",
    popularity: 86
  },
  {
    id: "patent-investigator",
    name: "Patent Investigator",
    category: "research",
    description: "Comprehensive patent landscape analysis with freedom-to-operate assessments. Identifies patent opportunities, risks, and competitive positioning for innovation strategy.",
    shortDesc: "Navigate patent landscapes with confidence",
    tokenSavings: "83%",
    timeSavings: "25hrs per analysis",
    useCases: ["Patent searches", "Freedom to operate", "Patent landscaping", "Innovation mapping"],
    features: ["Prior art search", "Patent clustering", "Legal status", "Citation analysis"],
    inputTypes: ["Technology descriptions", "Patent numbers", "Keywords"],
    outputTypes: ["Patent landscape", "FTO report", "Innovation gaps"],
    difficulty: "advanced",
    popularity: 79
  },
  {
    id: "consumer-insights-analyst",
    name: "Consumer Insights Analyst",
    category: "research",
    description: "Deep consumer behavior analysis with psychographic profiling and preference mapping. Transforms market research data into actionable customer intelligence.",
    shortDesc: "Understand your customers deeply",
    tokenSavings: "81%",
    timeSavings: "18hrs per study",
    useCases: ["Consumer profiling", "Behavior analysis", "Journey mapping", "Preference research"],
    features: ["Behavioral segmentation", "Journey analysis", "Sentiment tracking", "Preference modeling"],
    inputTypes: ["Survey data", "Interview transcripts", "Social media"],
    outputTypes: ["Consumer profiles", "Journey maps", "Insights report"],
    difficulty: "intermediate",
    popularity: 85
  },
  {
    id: "scientific-literature-miner",
    name: "Scientific Literature Miner",
    category: "research",
    description: "Extract and synthesize insights from vast scientific literature. Accelerates research discovery with automated paper analysis and knowledge extraction.",
    shortDesc: "Mine scientific papers for breakthrough insights",
    tokenSavings: "79%",
    timeSavings: "30hrs per domain",
    useCases: ["Literature mining", "Knowledge extraction", "Research synthesis", "Discovery acceleration"],
    features: ["Paper summarization", "Concept extraction", "Method analysis", "Result synthesis"],
    inputTypes: ["Research papers", "Abstracts", "Citations"],
    outputTypes: ["Knowledge map", "Research summary", "Method database"],
    difficulty: "advanced",
    popularity: 82
  },
  {
    id: "investment-research-analyst",
    name: "Investment Research Analyst",
    category: "research",
    description: "Comprehensive investment analysis with financial modeling and risk assessment. Provides institutional-grade research for investment decisions and portfolio management.",
    shortDesc: "Professional investment analysis and due diligence",
    tokenSavings: "76%",
    timeSavings: "22hrs per analysis",
    useCases: ["Stock analysis", "Due diligence", "Sector research", "Risk assessment"],
    features: ["Financial modeling", "Valuation analysis", "Risk metrics", "Peer comparison"],
    inputTypes: ["Financial statements", "Market data", "Company reports"],
    outputTypes: ["Investment report", "Valuation model", "Risk analysis"],
    difficulty: "advanced",
    popularity: 90,
    badge: "Premium"
  }
];

export function getAgentsByCategory(category: string): Agent[] {
  return agents.filter(agent => agent.category === category);
}

export function getAgentById(id: string): Agent | undefined {
  return agents.find(agent => agent.id === id);
}

export function getPopularAgents(limit: number = 10): Agent[] {
  return agents
    .sort((a, b) => b.popularity - a.popularity)
    .slice(0, limit);
}

export function searchAgents(query: string): Agent[] {
  const lowercaseQuery = query.toLowerCase();
  return agents.filter(agent => 
    agent.name.toLowerCase().includes(lowercaseQuery) ||
    agent.description.toLowerCase().includes(lowercaseQuery) ||
    agent.category.toLowerCase().includes(lowercaseQuery) ||
    agent.useCases.some(useCase => useCase.toLowerCase().includes(lowercaseQuery))
  );
}
