export interface Tool {
  id: string
  name: string
  category: string
  subcategory?: string
  logo: string
  description: string
  website: string
  company: string
  rating: number
  users: string
  pricing: {
    type: 'free' | 'freemium' | 'paid' | 'usage-based' | 'enterprise'
    free?: boolean
    starting?: number
    unit?: string
    details?: string
  }
  features: string[]
  pros: string[]
  cons: string[]
  useCases: string[]
  integrations: string[]
  platforms: string[]
  tags: string[]
  metrics: {
    performance: number
    features: number
    ease: number
    support: number
    value: number
    innovation: number
  }
}

export const toolsDatabase: Tool[] = [
  // AI CODING ASSISTANTS
  {
    id: 'cursor',
    name: 'Cursor',
    category: 'AI Coding',
    subcategory: 'IDE',
    logo: '🎯',
    description: 'AI-first code editor with GPT-4 integration',
    website: 'https://cursor.sh',
    company: 'Cursor Inc.',
    rating: 4.8,
    users: '500K+',
    pricing: { type: 'paid', starting: 20, unit: 'month', details: '$20/mo or $192/year' },
    features: ['GPT-4 Integration', 'Multi-file Editing', 'Chat Interface', 'Custom Models', 'Code Generation', 'Refactoring'],
    pros: ['Most advanced AI', 'Great for complex projects', 'Fast performance'],
    cons: ['Higher price', 'Requires internet', 'Learning curve'],
    useCases: ['Complex development', 'Full-stack projects', 'AI-heavy workflows'],
    integrations: ['GitHub', 'GitLab', 'VS Code extensions'],
    platforms: ['Windows', 'Mac', 'Linux'],
    tags: ['ai', 'ide', 'gpt-4', 'coding'],
    metrics: { performance: 95, features: 92, ease: 85, support: 82, value: 84, innovation: 96 }
  },
  {
    id: 'github-copilot',
    name: 'GitHub Copilot',
    category: 'AI Coding',
    subcategory: 'Extension',
    logo: '🐙',
    description: 'AI pair programmer by GitHub',
    website: 'https://copilot.github.com',
    company: 'GitHub/Microsoft',
    rating: 4.5,
    users: '1M+',
    pricing: { type: 'paid', starting: 10, unit: 'month', details: '$10/mo or $100/year' },
    features: ['Code Completion', 'Multi-language', 'Chat Mode', 'PR Summaries', 'Doc Generation'],
    pros: ['GitHub integration', 'Affordable', 'Wide IDE support'],
    cons: ['Limited customization', 'No offline mode', 'Privacy concerns'],
    useCases: ['Daily coding', 'Open source', 'GitHub projects'],
    integrations: ['VS Code', 'JetBrains', 'Neovim', 'GitHub'],
    platforms: ['Windows', 'Mac', 'Linux', 'Web'],
    tags: ['ai', 'github', 'completion', 'coding'],
    metrics: { performance: 88, features: 85, ease: 92, support: 90, value: 93, innovation: 87 }
  },
  {
    id: 'codeium',
    name: 'Codeium',
    category: 'AI Coding',
    subcategory: 'Extension',
    logo: '⚡',
    description: 'Free AI code completion',
    website: 'https://codeium.com',
    company: 'Codeium',
    rating: 4.6,
    users: '300K+',
    pricing: { type: 'freemium', free: true, starting: 0, details: 'Free forever, Pro at $12/mo' },
    features: ['Code Completion', 'Chat', 'Search', 'Multi-IDE', '70+ Languages'],
    pros: ['Completely free', 'Privacy-focused', 'Good performance'],
    cons: ['Less accurate', 'Smaller community', 'Limited features'],
    useCases: ['Personal projects', 'Learning', 'Budget teams'],
    integrations: ['VS Code', 'JetBrains', 'Vim', 'Emacs'],
    platforms: ['Windows', 'Mac', 'Linux'],
    tags: ['ai', 'free', 'completion', 'privacy'],
    metrics: { performance: 82, features: 78, ease: 88, support: 72, value: 100, innovation: 80 }
  },
  {
    id: 'windsurf',
    name: 'Windsurf IDE',
    category: 'AI Coding',
    subcategory: 'IDE',
    logo: '🏄',
    description: 'Flow-based AI IDE',
    website: 'https://windsurf.ai',
    company: 'Codeium',
    rating: 4.7,
    users: '100K+',
    pricing: { type: 'paid', starting: 15, unit: 'month', details: '$15/mo' },
    features: ['Flow UI', 'Voice Commands', 'AI Native', 'Collaboration', 'Real-time'],
    pros: ['Innovative UI', 'Voice control', 'Fast iteration'],
    cons: ['New platform', 'Limited ecosystem', 'Beta features'],
    useCases: ['Rapid prototyping', 'AI development', 'Innovation'],
    integrations: ['GitHub', 'Docker', 'Cloud providers'],
    platforms: ['Windows', 'Mac', 'Linux'],
    tags: ['ai', 'ide', 'flow', 'voice'],
    metrics: { performance: 88, features: 86, ease: 82, support: 78, value: 85, innovation: 94 }
  },
  {
    id: 'tabnine',
    name: 'Tabnine',
    category: 'AI Coding',
    subcategory: 'Extension',
    logo: '🤖',
    description: 'AI code completion with privacy',
    website: 'https://tabnine.com',
    company: 'Tabnine',
    rating: 4.4,
    users: '500K+',
    pricing: { type: 'freemium', free: true, starting: 12, unit: 'month' },
    features: ['Local AI', 'Team Training', 'Privacy Mode', 'Multi-IDE'],
    pros: ['Private option', 'Team features', 'Customizable'],
    cons: ['Less accurate', 'Resource heavy', 'Setup complexity'],
    useCases: ['Enterprise', 'Privacy-focused', 'Team coding'],
    integrations: ['All major IDEs'],
    platforms: ['Windows', 'Mac', 'Linux'],
    tags: ['ai', 'privacy', 'enterprise', 'local'],
    metrics: { performance: 80, features: 82, ease: 78, support: 85, value: 81, innovation: 79 }
  },
  {
    id: 'replit-ai',
    name: 'Replit AI',
    category: 'AI Coding',
    subcategory: 'Cloud IDE',
    logo: '🔄',
    description: 'Cloud IDE with AI assistance',
    website: 'https://replit.com',
    company: 'Replit',
    rating: 4.3,
    users: '20M+',
    pricing: { type: 'freemium', free: true, starting: 7, unit: 'month' },
    features: ['Cloud IDE', 'AI Chat', 'Deployment', 'Collaboration', 'Mobile'],
    pros: ['No setup', 'Free tier', 'Easy deploy'],
    cons: ['Cloud only', 'Limited resources', 'Internet required'],
    useCases: ['Learning', 'Prototyping', 'Teaching'],
    integrations: ['GitHub', 'Custom domains'],
    platforms: ['Web', 'iOS', 'Android'],
    tags: ['cloud', 'ai', 'education', 'deployment'],
    metrics: { performance: 75, features: 80, ease: 92, support: 78, value: 88, innovation: 83 }
  },

  // API MODELS
  {
    id: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    category: 'AI Models',
    subcategory: 'LLM',
    logo: '🧠',
    description: 'OpenAI\'s most capable model',
    website: 'https://openai.com',
    company: 'OpenAI',
    rating: 4.9,
    users: '10M+',
    pricing: { type: 'usage-based', starting: 0.01, unit: '1K tokens', details: '$0.01 input, $0.03 output per 1K' },
    features: ['128K Context', 'Vision', 'Functions', 'JSON Mode', 'DALL-E 3'],
    pros: ['Best performance', 'Huge context', 'Multimodal'],
    cons: ['Expensive', 'Rate limits', 'No fine-tuning'],
    useCases: ['Complex apps', 'Enterprise', 'Research'],
    integrations: ['All platforms via API'],
    platforms: ['API'],
    tags: ['llm', 'api', 'gpt-4', 'multimodal'],
    metrics: { performance: 98, features: 95, ease: 90, support: 88, value: 80, innovation: 97 }
  },
  {
    id: 'claude-3-opus',
    name: 'Claude 3 Opus',
    category: 'AI Models',
    subcategory: 'LLM',
    logo: '🎭',
    description: 'Anthropic\'s flagship model',
    website: 'https://anthropic.com',
    company: 'Anthropic',
    rating: 4.8,
    users: '5M+',
    pricing: { type: 'usage-based', starting: 0.015, unit: '1K tokens', details: '$0.015 input, $0.075 output per 1K' },
    features: ['200K Context', 'Vision', 'Safety', 'Analysis', 'Code'],
    pros: ['Huge context', 'Safe outputs', 'Great reasoning'],
    cons: ['Most expensive', 'No functions', 'Limited access'],
    useCases: ['Document analysis', 'Research', 'Safety-critical'],
    integrations: ['API', 'AWS Bedrock'],
    platforms: ['API'],
    tags: ['llm', 'api', 'claude', 'safety'],
    metrics: { performance: 96, features: 90, ease: 89, support: 92, value: 75, innovation: 94 }
  },
  {
    id: 'gemini-pro',
    name: 'Gemini Pro',
    category: 'AI Models',
    subcategory: 'LLM',
    logo: '✨',
    description: 'Google\'s multimodal AI',
    website: 'https://ai.google.dev',
    company: 'Google',
    rating: 4.5,
    users: '3M+',
    pricing: { type: 'freemium', free: true, starting: 0.00025, unit: '1K tokens', details: 'Free tier: 60 QPM' },
    features: ['32K Context', 'Vision', 'Free Tier', 'Fast', 'Embeddings'],
    pros: ['Free tier', 'Fast response', 'Google ecosystem'],
    cons: ['Smaller context', 'Less consistent', 'Geographic limits'],
    useCases: ['Prototyping', 'Small apps', 'Budget projects'],
    integrations: ['Google Cloud', 'Vertex AI'],
    platforms: ['API'],
    tags: ['llm', 'api', 'google', 'free'],
    metrics: { performance: 86, features: 84, ease: 88, support: 85, value: 95, innovation: 88 }
  },
  {
    id: 'mistral-large',
    name: 'Mistral Large',
    category: 'AI Models',
    subcategory: 'LLM',
    logo: '🌪️',
    description: 'European AI model',
    website: 'https://mistral.ai',
    company: 'Mistral AI',
    rating: 4.4,
    users: '1M+',
    pricing: { type: 'usage-based', starting: 0.004, unit: '1K tokens' },
    features: ['32K Context', 'Fast', 'EU Compliant', 'JSON Output'],
    pros: ['Cost-effective', 'EU hosting', 'Good performance'],
    cons: ['Smaller context', 'Less features', 'Newer'],
    useCases: ['EU projects', 'Cost-sensitive', 'Standard tasks'],
    integrations: ['API', 'Azure'],
    platforms: ['API'],
    tags: ['llm', 'api', 'europe', 'mistral'],
    metrics: { performance: 84, features: 80, ease: 86, support: 78, value: 90, innovation: 82 }
  },
  {
    id: 'llama-3-70b',
    name: 'Llama 3 70B',
    category: 'AI Models',
    subcategory: 'Open Source',
    logo: '🦙',
    description: 'Meta\'s open-source LLM',
    website: 'https://llama.meta.com',
    company: 'Meta',
    rating: 4.6,
    users: '2M+',
    pricing: { type: 'free', free: true, details: 'Self-hosted or cloud providers' },
    features: ['Open Source', 'Fine-tunable', '8K Context', 'Commercial Use'],
    pros: ['Free to use', 'Customizable', 'No limits'],
    cons: ['Self-hosting', 'Smaller context', 'Resource heavy'],
    useCases: ['Custom apps', 'Fine-tuning', 'Research'],
    integrations: ['All platforms'],
    platforms: ['Self-hosted', 'Cloud'],
    tags: ['llm', 'open-source', 'meta', 'free'],
    metrics: { performance: 85, features: 82, ease: 70, support: 65, value: 100, innovation: 86 }
  },

  // MCP SERVERS
  {
    id: 'mcp-filesystem',
    name: 'MCP Filesystem',
    category: 'MCP Servers',
    subcategory: 'Core',
    logo: '📁',
    description: 'File system operations for Claude',
    website: 'https://github.com/anthropics/mcp',
    company: 'Anthropic',
    rating: 4.6,
    users: '50K+',
    pricing: { type: 'free', free: true },
    features: ['File Ops', 'Search', 'Permissions', 'Watch Mode'],
    pros: ['Essential tool', 'Well-maintained', 'Secure'],
    cons: ['Local only', 'Basic features', 'No cloud'],
    useCases: ['File automation', 'Claude integration', 'Local tasks'],
    integrations: ['Claude', 'VS Code'],
    platforms: ['Windows', 'Mac', 'Linux'],
    tags: ['mcp', 'filesystem', 'claude', 'automation'],
    metrics: { performance: 90, features: 85, ease: 83, support: 80, value: 100, innovation: 82 }
  },
  {
    id: 'mcp-github',
    name: 'MCP GitHub',
    category: 'MCP Servers',
    subcategory: 'Integration',
    logo: '🔗',
    description: 'GitHub integration for Claude',
    website: 'https://github.com/anthropics/mcp',
    company: 'Anthropic',
    rating: 4.7,
    users: '30K+',
    pricing: { type: 'free', free: true },
    features: ['Repo Access', 'PR Management', 'Issues', 'Actions'],
    pros: ['GitHub automation', 'Full API access', 'Free'],
    cons: ['GitHub only', 'Setup required', 'Token needed'],
    useCases: ['Dev automation', 'PR reviews', 'Issue management'],
    integrations: ['Claude', 'GitHub'],
    platforms: ['All'],
    tags: ['mcp', 'github', 'automation', 'dev'],
    metrics: { performance: 88, features: 90, ease: 78, support: 82, value: 100, innovation: 85 }
  },
  {
    id: 'mcp-slack',
    name: 'MCP Slack',
    category: 'MCP Servers',
    subcategory: 'Communication',
    logo: '💬',
    description: 'Slack integration for Claude',
    website: 'https://github.com/anthropics/mcp',
    company: 'Community',
    rating: 4.5,
    users: '20K+',
    pricing: { type: 'free', free: true },
    features: ['Messages', 'Channels', 'DMs', 'Search'],
    pros: ['Team automation', 'Free', 'Useful'],
    cons: ['Slack only', 'Auth complex', 'Rate limits'],
    useCases: ['Team updates', 'Notifications', 'Chat automation'],
    integrations: ['Claude', 'Slack'],
    platforms: ['All'],
    tags: ['mcp', 'slack', 'chat', 'team'],
    metrics: { performance: 85, features: 82, ease: 75, support: 70, value: 100, innovation: 80 }
  },

  // DEV TOOLS
  {
    id: 'docker',
    name: 'Docker',
    category: 'Dev Tools',
    subcategory: 'Containers',
    logo: '🐳',
    description: 'Container platform',
    website: 'https://docker.com',
    company: 'Docker Inc.',
    rating: 4.7,
    users: '20M+',
    pricing: { type: 'freemium', free: true, starting: 5, unit: 'month' },
    features: ['Containers', 'Compose', 'Registry', 'Kubernetes'],
    pros: ['Industry standard', 'Portable', 'Ecosystem'],
    cons: ['Learning curve', 'Resource use', 'Complexity'],
    useCases: ['Deployment', 'Development', 'Microservices'],
    integrations: ['All CI/CD', 'Cloud providers'],
    platforms: ['Windows', 'Mac', 'Linux'],
    tags: ['containers', 'devops', 'deployment'],
    metrics: { performance: 92, features: 94, ease: 75, support: 88, value: 90, innovation: 85 }
  },
  {
    id: 'vscode',
    name: 'VS Code',
    category: 'Dev Tools',
    subcategory: 'IDE',
    logo: '💻',
    description: 'Code editor by Microsoft',
    website: 'https://code.visualstudio.com',
    company: 'Microsoft',
    rating: 4.8,
    users: '30M+',
    pricing: { type: 'free', free: true },
    features: ['Extensions', 'Git', 'Debug', 'Terminal', 'Remote'],
    pros: ['Free', 'Extensible', 'Popular'],
    cons: ['Resource heavy', 'Microsoft', 'Electron-based'],
    useCases: ['All development', 'Any language', 'Remote work'],
    integrations: ['Everything'],
    platforms: ['Windows', 'Mac', 'Linux', 'Web'],
    tags: ['ide', 'editor', 'microsoft', 'free'],
    metrics: { performance: 88, features: 96, ease: 90, support: 92, value: 100, innovation: 87 }
  },
  {
    id: 'postman',
    name: 'Postman',
    category: 'Dev Tools',
    subcategory: 'API Testing',
    logo: '📮',
    description: 'API development platform',
    website: 'https://postman.com',
    company: 'Postman',
    rating: 4.5,
    users: '25M+',
    pricing: { type: 'freemium', free: true, starting: 12, unit: 'month' },
    features: ['API Testing', 'Documentation', 'Mocking', 'Monitoring'],
    pros: ['Comprehensive', 'Team features', 'Free tier'],
    cons: ['Heavy app', 'Cloud sync', 'Pricing jumps'],
    useCases: ['API development', 'Testing', 'Documentation'],
    integrations: ['CI/CD', 'Git'],
    platforms: ['Windows', 'Mac', 'Linux', 'Web'],
    tags: ['api', 'testing', 'rest', 'development'],
    metrics: { performance: 82, features: 92, ease: 85, support: 86, value: 84, innovation: 80 }
  },

  // UI/DESIGN TOOLS
  {
    id: 'v0',
    name: 'v0',
    category: 'AI Design',
    subcategory: 'UI Generation',
    logo: '⚡',
    description: 'AI UI generation by Vercel',
    website: 'https://v0.dev',
    company: 'Vercel',
    rating: 4.6,
    users: '500K+',
    pricing: { type: 'freemium', free: true, starting: 20, unit: 'month', details: 'Credits system' },
    features: ['UI Generation', 'React/Next.js', 'Tailwind', 'Shadcn'],
    pros: ['Fast generation', 'Production ready', 'Modern stack'],
    cons: ['Credits limit', 'React only', 'Vercel ecosystem'],
    useCases: ['UI prototyping', 'Landing pages', 'Components'],
    integrations: ['Vercel', 'Next.js'],
    platforms: ['Web'],
    tags: ['ai', 'ui', 'design', 'react'],
    metrics: { performance: 88, features: 85, ease: 91, support: 82, value: 86, innovation: 92 }
  },
  {
    id: 'galileo-ai',
    name: 'Galileo AI',
    category: 'AI Design',
    subcategory: 'UI Generation',
    logo: '🎨',
    description: 'AI design generation',
    website: 'https://galileo.ai',
    company: 'Galileo AI',
    rating: 4.4,
    users: '100K+',
    pricing: { type: 'paid', starting: 19, unit: 'month' },
    features: ['Figma Export', 'Full Designs', 'Editable', 'Components'],
    pros: ['Full designs', 'Figma integration', 'High quality'],
    cons: ['Expensive', 'Limited edits', 'Waitlist'],
    useCases: ['Design teams', 'Rapid prototyping', 'Mockups'],
    integrations: ['Figma'],
    platforms: ['Web'],
    tags: ['ai', 'design', 'figma', 'ui'],
    metrics: { performance: 85, features: 87, ease: 83, support: 78, value: 79, innovation: 90 }
  },

  // AUTOMATION TOOLS
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'Automation',
    subcategory: 'Workflow',
    logo: '⚡',
    description: 'Workflow automation platform',
    website: 'https://zapier.com',
    company: 'Zapier',
    rating: 4.4,
    users: '2M+',
    pricing: { type: 'freemium', free: true, starting: 19.99, unit: 'month' },
    features: ['5000+ Apps', 'Multi-step', 'Filters', 'Scheduling'],
    pros: ['Most integrations', 'No code', 'Reliable'],
    cons: ['Expensive scaling', 'Execution limits', 'Simple logic only'],
    useCases: ['Business automation', 'Integration', 'No-code'],
    integrations: ['5000+ apps'],
    platforms: ['Web'],
    tags: ['automation', 'nocode', 'integration', 'workflow'],
    metrics: { performance: 86, features: 94, ease: 92, support: 88, value: 78, innovation: 80 }
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'Automation',
    subcategory: 'Workflow',
    logo: '🔄',
    description: 'Open-source automation',
    website: 'https://n8n.io',
    company: 'n8n',
    rating: 4.6,
    users: '500K+',
    pricing: { type: 'freemium', free: true, starting: 20, unit: 'month', details: 'Self-hosted free' },
    features: ['Open Source', 'Self-host', 'Code Option', '400+ Apps'],
    pros: ['Self-hosted option', 'Flexible', 'Fair pricing'],
    cons: ['Fewer integrations', 'Technical setup', 'Smaller community'],
    useCases: ['Dev automation', 'Self-hosted', 'Complex workflows'],
    integrations: ['400+ apps'],
    platforms: ['Web', 'Docker'],
    tags: ['automation', 'opensource', 'workflow', 'selfhosted'],
    metrics: { performance: 84, features: 88, ease: 78, support: 82, value: 92, innovation: 86 }
  },
  {
    id: 'make',
    name: 'Make (Integromat)',
    category: 'Automation',
    subcategory: 'Workflow',
    logo: '🔧',
    description: 'Visual automation platform',
    website: 'https://make.com',
    company: 'Make',
    rating: 4.5,
    users: '1M+',
    pricing: { type: 'freemium', free: true, starting: 9, unit: 'month' },
    features: ['Visual Builder', '1000+ Apps', 'Data Ops', 'Scenarios'],
    pros: ['Visual design', 'Powerful ops', 'Good pricing'],
    cons: ['Learning curve', 'Complex UI', 'Documentation'],
    useCases: ['Complex automation', 'Data processing', 'Visual workflows'],
    integrations: ['1000+ apps'],
    platforms: ['Web'],
    tags: ['automation', 'visual', 'integration', 'workflow'],
    metrics: { performance: 85, features: 90, ease: 75, support: 80, value: 88, innovation: 84 }
  },

  // DATABASE & BACKEND
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Backend',
    subcategory: 'BaaS',
    logo: '🔥',
    description: 'Open-source Firebase alternative',
    website: 'https://supabase.com',
    company: 'Supabase',
    rating: 4.7,
    users: '500K+',
    pricing: { type: 'freemium', free: true, starting: 25, unit: 'month' },
    features: ['Postgres', 'Auth', 'Storage', 'Realtime', 'Vector'],
    pros: ['Open source', 'Postgres', 'Generous free tier'],
    cons: ['Newer platform', 'Postgres only', 'Cold starts'],
    useCases: ['Full-stack apps', 'SaaS', 'Startups'],
    integrations: ['All frameworks'],
    platforms: ['Cloud', 'Self-hosted'],
    tags: ['database', 'backend', 'postgres', 'baas'],
    metrics: { performance: 88, features: 90, ease: 86, support: 84, value: 94, innovation: 89 }
  },
  {
    id: 'firebase',
    name: 'Firebase',
    category: 'Backend',
    subcategory: 'BaaS',
    logo: '🔶',
    description: 'Google\'s app development platform',
    website: 'https://firebase.google.com',
    company: 'Google',
    rating: 4.5,
    users: '3M+',
    pricing: { type: 'freemium', free: true, details: 'Pay as you go' },
    features: ['NoSQL', 'Auth', 'Hosting', 'Functions', 'Analytics'],
    pros: ['Google scale', 'Easy setup', 'Mobile SDKs'],
    cons: ['Vendor lock-in', 'NoSQL only', 'Cost scaling'],
    useCases: ['Mobile apps', 'Web apps', 'MVPs'],
    integrations: ['Google Cloud'],
    platforms: ['Cloud'],
    tags: ['database', 'backend', 'google', 'baas'],
    metrics: { performance: 90, features: 92, ease: 91, support: 88, value: 85, innovation: 82 }
  },
  {
    id: 'planetscale',
    name: 'PlanetScale',
    category: 'Backend',
    subcategory: 'Database',
    logo: '🌍',
    description: 'Serverless MySQL platform',
    website: 'https://planetscale.com',
    company: 'PlanetScale',
    rating: 4.6,
    users: '100K+',
    pricing: { type: 'freemium', free: true, starting: 29, unit: 'month' },
    features: ['MySQL', 'Branching', 'Serverless', 'Global'],
    pros: ['Database branching', 'Scalable', 'Developer friendly'],
    cons: ['MySQL only', 'No foreign keys', 'Learning curve'],
    useCases: ['Scalable apps', 'Global apps', 'MySQL projects'],
    integrations: ['ORMs', 'Frameworks'],
    platforms: ['Cloud'],
    tags: ['database', 'mysql', 'serverless', 'scaling'],
    metrics: { performance: 91, features: 87, ease: 82, support: 85, value: 86, innovation: 92 }
  },

  // MONITORING & ANALYTICS
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'Monitoring',
    subcategory: 'Error Tracking',
    logo: '🚨',
    description: 'Error tracking and performance',
    website: 'https://sentry.io',
    company: 'Sentry',
    rating: 4.6,
    users: '2M+',
    pricing: { type: 'freemium', free: true, starting: 26, unit: 'month' },
    features: ['Error Tracking', 'Performance', 'Profiling', 'Replays'],
    pros: ['Comprehensive', 'All platforms', 'Good free tier'],
    cons: ['Can be noisy', 'Complex setup', 'Data volume costs'],
    useCases: ['Production apps', 'Error monitoring', 'Performance'],
    integrations: ['All platforms', 'CI/CD'],
    platforms: ['Cloud', 'Self-hosted'],
    tags: ['monitoring', 'errors', 'performance', 'debugging'],
    metrics: { performance: 89, features: 93, ease: 81, support: 87, value: 85, innovation: 88 }
  },
  {
    id: 'posthog',
    name: 'PostHog',
    category: 'Monitoring',
    subcategory: 'Analytics',
    logo: '🦔',
    description: 'Open-source product analytics',
    website: 'https://posthog.com',
    company: 'PostHog',
    rating: 4.5,
    users: '300K+',
    pricing: { type: 'freemium', free: true, starting: 0, details: 'Generous free tier' },
    features: ['Analytics', 'Sessions', 'Feature Flags', 'A/B Tests'],
    pros: ['Open source', 'All-in-one', 'Privacy-friendly'],
    cons: ['Resource heavy', 'Complex features', 'Learning curve'],
    useCases: ['Product analytics', 'User tracking', 'Experiments'],
    integrations: ['All platforms'],
    platforms: ['Cloud', 'Self-hosted'],
    tags: ['analytics', 'opensource', 'privacy', 'product'],
    metrics: { performance: 84, features: 91, ease: 76, support: 82, value: 92, innovation: 87 }
  },

  // DEPLOYMENT & HOSTING
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'Hosting',
    subcategory: 'Edge Platform',
    logo: '▲',
    description: 'Frontend cloud platform',
    website: 'https://vercel.com',
    company: 'Vercel',
    rating: 4.7,
    users: '1M+',
    pricing: { type: 'freemium', free: true, starting: 20, unit: 'month' },
    features: ['Edge Functions', 'Next.js', 'Preview', 'Analytics'],
    pros: ['Fast deploys', 'Great DX', 'Next.js integration'],
    cons: ['Vendor lock-in', 'Pricing jumps', 'Limited backend'],
    useCases: ['Next.js apps', 'Static sites', 'Frontend'],
    integrations: ['GitHub', 'GitLab', 'Bitbucket'],
    platforms: ['Cloud'],
    tags: ['hosting', 'deployment', 'nextjs', 'edge'],
    metrics: { performance: 94, features: 88, ease: 95, support: 86, value: 85, innovation: 91 }
  },
  {
    id: 'netlify',
    name: 'Netlify',
    category: 'Hosting',
    subcategory: 'JAMstack',
    logo: '🔷',
    description: 'Modern web development platform',
    website: 'https://netlify.com',
    company: 'Netlify',
    rating: 4.6,
    users: '2M+',
    pricing: { type: 'freemium', free: true, starting: 19, unit: 'month' },
    features: ['Deploy Previews', 'Forms', 'Functions', 'Identity'],
    pros: ['Easy setup', 'Good free tier', 'Great features'],
    cons: ['Build minutes limit', 'Function limits', 'Less Next.js support'],
    useCases: ['Static sites', 'JAMstack', 'SPAs'],
    integrations: ['Git providers'],
    platforms: ['Cloud'],
    tags: ['hosting', 'jamstack', 'deployment', 'static'],
    metrics: { performance: 90, features: 89, ease: 93, support: 85, value: 88, innovation: 86 }
  },
  {
    id: 'railway',
    name: 'Railway',
    category: 'Hosting',
    subcategory: 'PaaS',
    logo: '🚂',
    description: 'Modern app deployment platform',
    website: 'https://railway.app',
    company: 'Railway',
    rating: 4.5,
    users: '200K+',
    pricing: { type: 'freemium', free: true, starting: 5, unit: 'month', details: 'Usage-based' },
    features: ['Databases', 'Docker', 'Templates', 'Environments'],
    pros: ['Simple pricing', 'Good DX', 'Database included'],
    cons: ['Newer platform', 'Limited regions', 'Smaller community'],
    useCases: ['Full-stack apps', 'APIs', 'Databases'],
    integrations: ['GitHub'],
    platforms: ['Cloud'],
    tags: ['hosting', 'paas', 'deployment', 'database'],
    metrics: { performance: 86, features: 85, ease: 90, support: 80, value: 89, innovation: 88 }
  },

  // TESTING TOOLS
  {
    id: 'playwright',
    name: 'Playwright',
    category: 'Testing',
    subcategory: 'E2E Testing',
    logo: '🎭',
    description: 'Web testing and automation',
    website: 'https://playwright.dev',
    company: 'Microsoft',
    rating: 4.8,
    users: '1M+',
    pricing: { type: 'free', free: true },
    features: ['Cross-browser', 'Auto-wait', 'Tracing', 'Mobile'],
    pros: ['Reliable', 'Fast', 'Great debugging'],
    cons: ['Learning curve', 'Resource heavy', 'Setup complexity'],
    useCases: ['E2E testing', 'Web scraping', 'Automation'],
    integrations: ['CI/CD', 'Test runners'],
    platforms: ['All'],
    tags: ['testing', 'e2e', 'automation', 'microsoft'],
    metrics: { performance: 93, features: 95, ease: 80, support: 90, value: 100, innovation: 92 }
  },
  {
    id: 'cypress',
    name: 'Cypress',
    category: 'Testing',
    subcategory: 'E2E Testing',
    logo: '🌲',
    description: 'JavaScript E2E testing',
    website: 'https://cypress.io',
    company: 'Cypress.io',
    rating: 4.6,
    users: '2M+',
    pricing: { type: 'freemium', free: true, starting: 75, unit: 'month' },
    features: ['Time Travel', 'Real Browser', 'Dashboard', 'Component'],
    pros: ['Great DX', 'Easy setup', 'Good docs'],
    cons: ['Chrome-focused', 'Async limitations', 'Dashboard pricing'],
    useCases: ['Frontend testing', 'E2E', 'Component testing'],
    integrations: ['CI/CD'],
    platforms: ['All'],
    tags: ['testing', 'e2e', 'javascript', 'frontend'],
    metrics: { performance: 88, features: 90, ease: 91, support: 88, value: 84, innovation: 86 }
  },

  // COMMUNICATION TOOLS
  {
    id: 'discord',
    name: 'Discord',
    category: 'Communication',
    subcategory: 'Chat',
    logo: '💬',
    description: 'Chat and voice platform',
    website: 'https://discord.com',
    company: 'Discord',
    rating: 4.5,
    users: '150M+',
    pricing: { type: 'freemium', free: true, starting: 9.99, unit: 'month' },
    features: ['Voice', 'Video', 'Screen Share', 'Bots', 'Communities'],
    pros: ['Free tier', 'Great for communities', 'Bot ecosystem'],
    cons: ['Gaming focused', 'Moderation needs', 'Not enterprise'],
    useCases: ['Communities', 'Gaming', 'Team chat'],
    integrations: ['Bots', 'Webhooks'],
    platforms: ['All'],
    tags: ['chat', 'voice', 'community', 'gaming'],
    metrics: { performance: 90, features: 88, ease: 89, support: 82, value: 93, innovation: 85 }
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'Communication',
    subcategory: 'Team Chat',
    logo: '#',
    description: 'Business communication platform',
    website: 'https://slack.com',
    company: 'Slack/Salesforce',
    rating: 4.4,
    users: '20M+',
    pricing: { type: 'freemium', free: true, starting: 7.25, unit: 'month' },
    features: ['Channels', 'DMs', 'Integrations', 'Huddles', 'Canvas'],
    pros: ['Enterprise ready', 'Many integrations', 'Reliable'],
    cons: ['Message limits', 'Expensive scaling', 'Resource heavy'],
    useCases: ['Business', 'Team collaboration', 'Enterprise'],
    integrations: ['2000+ apps'],
    platforms: ['All'],
    tags: ['chat', 'business', 'team', 'enterprise'],
    metrics: { performance: 88, features: 92, ease: 87, support: 90, value: 80, innovation: 82 }
  }
]

export function getToolsByCategory(category: string): Tool[] {
  return toolsDatabase.filter(tool => tool.category === category)
}

export function getToolById(id: string): Tool | undefined {
  return toolsDatabase.find(tool => tool.id === id)
}

export function searchTools(query: string): Tool[] {
  const q = query.toLowerCase()
  return toolsDatabase.filter(tool => 
    tool.name.toLowerCase().includes(q) ||
    tool.description.toLowerCase().includes(q) ||
    tool.tags.some(tag => tag.includes(q)) ||
    tool.category.toLowerCase().includes(q)
  )
}

export function getCategories(): string[] {
  return [...new Set(toolsDatabase.map(tool => tool.category))]
}

export function getToolCount(): number {
  return toolsDatabase.length
}